### ISSUE TITLE
拉取镜像报错requested access to the resource is denied

### ISSUE THREAD

**Issue by goodryb** [kubesre/docker-registry-mirrors#7]
你好，拉取镜像的时候提示下面的错误

# docker pull dhub.kubesre.xyz/quark-auto-save:latest
Error response from daemon: pull access denied for dhub.kubesre.xyz/quark-auto-save, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by gebangfeng** [comment]
只能拉取公开仓库的哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Goodryb ***@***.***&gt;
发送时间: 2024年6月18日 18:22
收件人: kubesre/docker-registry-mirrors ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kubesre/docker-registry-mirrors] 拉取镜像报错requested access to the resource is denied (Issue #7)





 
你好，拉取镜像的时候提示下面的错误
 
docker pull dhub.kubesre.xyz/quark-auto-save:latest
 
Error response from daemon: pull access denied for dhub.kubesre.xyz/quark-auto-save, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by goodryb** [comment]
@gebangfeng    原始镜像地址是    https://hub.docker.com/r/cp0204/quark-auto-save  这个应该是公开镜像吧

我在这里填写了镜像地址以后  https://dockerproxy.github.io/#/index  ，生成的镜像拉取命令就是  docker pull dhub.kubesre.xyz/quark-auto-save:latest

**Comment by gebangfeng** [comment]
docker pull dhub.kubesre.xyz/cp0204/quark-auto-save:latest
这样试试，网站生成逻辑可能有点问题，尽快优化

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Goodryb ***@***.***&gt;
发送时间: 2024年6月18日 18:57
收件人: kubesre/docker-registry-mirrors ***@***.***&gt;
抄送: 凡之 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [kubesre/docker-registry-mirrors] 拉取镜像报错requested access to the resource is denied (Issue #7)





 
@gebangfeng    原始镜像地址是    https://hub.docker.com/r/cp0204/quark-auto-save  这个应该是公开镜像吧
 
我在这里填写了镜像地址以后  https://dockerproxy.github.io/#/index  ，生成的镜像拉取命令就是  docker pull dhub.kubesre.xyz/quark-auto-save:latest

**Comment by goodryb** [comment]
> docker pull dhub.kubesre.xyz/cp0204/quark-auto-save:latest 这样试试，网站生成逻辑可能有点问题，尽快优化 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Goodryb ***@***.***&gt; 发送时间: 2024年6月18日 18:57 收件人: kubesre/docker-registry-mirrors ***@***.***&gt; 抄送: 凡之 ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [kubesre/docker-registry-mirrors] 拉取镜像报错requested access to the resource is denied (Issue #7) @gebangfeng 原始镜像地址是 https://hub.docker.com/r/cp0204/quark-auto-save 这个应该是公开镜像吧 我在这里填写了镜像地址以后 https://dockerproxy.github.io/#/index ，生成的镜像拉取命令就是 docker pull dhub.kubesre.xyz/quark-auto-save:latest — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

这样是可以的，看起来是丢失了中间的cp0204，多谢

**Comment by gebangfeng** [comment]
网站处理问题已解决，有问题随时联系



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Goodryb ***@***.***&gt;
发送时间: 2024年6月18日 19:07
收件人: kubesre/docker-registry-mirrors ***@***.***&gt;
抄送: 凡之 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [kubesre/docker-registry-mirrors] 拉取镜像报错requested access to the resource is denied (Issue #7)





  
docker pull dhub.kubesre.xyz/cp0204/quark-auto-save:latest 这样试试，网站生成逻辑可能有点问题，尽快优化 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Goodryb @.&gt; 发送时间: 2024年6月18日 18:57 收件人: kubesre/docker-registry-mirrors @.&gt; 抄送: 凡之 @.&gt;, Mention @.&gt; 主题: Re: [kubesre/docker-registry-mirrors] 拉取镜像报错requested access to the resource is denied (Issue #7) @gebangfeng 原始镜像地址是 https://hub.docker.com/r/cp0204/quark-auto-save 这个应该是公开镜像吧 我在这里填写了镜像地址以后 https://dockerproxy.github.io/#/index ，生成的镜像拉取命令就是 docker pull dhub.kubesre.xyz/quark-auto-save:latest — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
这样是可以的，看起来是丢失了中间的cp0204，多谢
